#Global configurations
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
- job_name: 'authenticator'
  metrics_path: '/prom'
  static_configs:
  - targets: ['authenticator:8090']
- job_name: 'orders'
  metrics_path: '/prom'
  static_configs:
  - targets: ['orders:9000']
- job_name: 'customers'
  metrics_path: '/prom'
  static_configs:
  - targets: ['customers:8080']
